[program:sql-playground]
command=/usr/bin/node /root/sql-playground/backend/src/server.js
directory=/root/sql-playground/backend
environment=NODE_ENV="production",NODE_PATH="/root/sql-playground/backend/node_modules"
user=root
group=root
autostart=true
autorestart=true
startretries=5
stdout_logfile=/tmp/sql-playground.stdout.log
stderr_logfile=/tmp/sql-playground.stderr.log
stopsignal=TERM
stopwaitsecs=10
